opencart/opencart-3

upload/system/library/db/mysqli.php
https://github.com/opencart/opencart/pull/10437/files
=> Fixed MySQLi PHP 8.1 warning

upload/system/library/db/mysqli.php
https://github.com/ADDCreative/opencart/commit/3c8fe306909853a9581dcc72bb143312a9dfa9a9
=> MySQLi code reverted

upload/catalog/view/theme/default/template/affiliate/register.twig
=> Fixed account custom fields not inserted in database when register from affiliate/register

upload/system/library/log.php
https://github.com/opencart/opencart/commit/21ef0ef4fe88f92086e4aff4221f081f034af378
=> Typo log.php

upload/catalog/view/theme/default/template/product/product.twig
d-none class is not on bootsrap 3
=> Added missing script type product.twig

upload/system/library/cart/customer.php
https://github.com/opencart/opencart/blob/master/upload/system/library/cart/customer.php
=> Fixed customer library warnings

upload/catalog/controller/common/cart.php
https://forum.opencart.com/viewtopic.php?t=229750
=> Fixed cart PHP 8.1 warning

upload/system/library/document.php
https://github.com/opencart/opencart/blob/master/upload/system/library/document.php#L131
=> Fixed javascript warnings

upload/admin/view/javascript/codemirror/lib/codemirror.js, upload/admin/view/javascript/codemirror/theme/pastel-on-dark.css, upload/admin/view/javascript/jquery/datetimepicker/moment/locales.js, upload/admin/view/javascript/jquery/flot/examples/examples.css, upload/admin/view/javascript/jquery/flot/examples/series-pie/index.html, upload/admin/view/javascript/jquery/jquery-ui/jquery-ui.css, upload/admin/view/javascript/jquery/jquery-ui/jquery-ui.structure.css, upload/admin/view/javascript/jquery/magnific/jquery.magnific-popup.js, upload/admin/view/javascript/jquery/magnific/magnific-popup.css, upload/admin/view/javascript/summernote/summernote.js, upload/admin/view/stylesheet/stylesheet.css, upload/catalog/controller/extension/payment/pp_standard.php, upload/catalog/model/extension/payment/bank_transfer.php, upload/catalog/model/extension/payment/cod.php, upload/catalog/model/extension/payment/free_checkout.php, upload/catalog/view/javascript/jquery/datetimepicker/moment/locales.js, upload/catalog/view/javascript/jquery/magnific/magnific-popup.css, upload/catalog/view/theme/default/stylesheet/stylesheet.css, upload/install/view/stylesheet/stylesheet.css
Replace
`public function getMethod(array $address, float $total): array {`
with
`public function getMethod(array $address): array {`
=> Remove float $total

upload/system/library/cart/cart.php, upload/system/storage/vendor/composer/autoload_files.php, upload/system/storage/vendor/composer/autoload_static.php, upload/system/storage/vendor/composer/installed.php
```
//'c964ee0ededf28c96ebd9db5099ef910' => $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
//'6e3fae29631ef280660b3cdad06f25a8' => $vendorDir . '/symfony/deprecation-contracts/function.php',
//'b067bc7112e384b61c701452d53a14a8' => $vendorDir . '/mtdowling/jmespath.php/src/JmesPath.php',
```
=================================================================
```
//'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
//'6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
//'b067bc7112e384b61c701452d53a14a8' => __DIR__ . '/..' . '/mtdowling/jmespath.php/src/JmesPath.php'
```
=================================================================
```
/*'symfony/deprecation-contracts' …
```
=>  Removed promises,deprecation-contracts,jmespath.php from composer

upload/admin/controller/customer/customer.php, upload/catalog/controller/account/login.php, upload/catalog/model/account/customer.php
Fix login from admin
Add login and token
=> Fix login from admin

upload/install/model/upgrade/1009.php
This pull request addresses an SQL issue that needs to be resolved in order to proceed with the upgrade process. The issue arises when attempting to upgrade the system to a newer version, and it hampers the smooth transition of the database.
=> Fix SQL Issue For Upgrade

upload/admin/controller/common/filemanager.php
I've reverted the changes to be the same as the current Maintenance branch.
=> Revert filemanager to maintenance branch

upload/catalog/controller/startup/seo_url.php
=> fixes the issue #184

README.md
Updated link like in the main project.
=> Update README.md - Updated license link

upload/admin/controller/localisation/currency.php, upload/admin/language/en-gb/localisation/currency.php, upload/admin/view/template/extension/currency/ecb.twig
Added some missing bugfixes for the usage of the ecb
=> Some more fixes for the ecb

upload/system/library/template/twig.php
https://github.com/opencart/opencart/blob/master/upload/system/library/template/twig.php#L122
=> Fixed PHP 8.3 warning error in twig.php

phpstan.neon
This solves the last PHPStan issue
=> Ignore false possitive from Event class conflict

upload/catalog/view/javascript/paypal/paypal.js
https://forum.opencart.com/viewtopic.php?t=232822#p865518
=> Paypal language bug - paypal.js

upload/admin/model/sale/order.php
If was removed by mistake from database....you can add back :)
=> Removed unused shipping_code from order model

upload/admin/view/template/design/layout_form.twig
With that modification you get
Could not load template design/layout_form
=> Fixed layout_form not loaded

upload/catalog/model/catalog/category.php
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/category.php#L91-L95
=> Fixed layout_id warning category model

upload/admin/controller/extension/payment/paypal.php
https://github.com/opencart/opencart/commit/4d0bccb8a518997fee3968c15cd6107e1c7d399f
=> Added Paypal Bugfix order info heading title from 3.0.x.x

upload/catalog/view/javascript/paypal/paypal.js
https://forum.opencart.com/viewtopic.php?t=232822#p865518
=> Added Checkout Paypal Language bug fix

upload/admin/view/stylesheet/stylesheet.css
Already exists
#header .nav > li.dropdown > a {
padding-left: 10px;
padding-right: 10px;
}
=> Dublicate Css removal
